name: Spring boot Java CI CD with Docker

on:
  push:
    branches: [ "master" ]

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

  setup-jdk:
    runs-on: ubuntu-latest
    #    needs: maven-build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/spring-application-github.jar spring-application-github-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: spring-application-github
          path: spring-application-github-${{ github.sha }}.jar

  #    sonarqube:
  #      runs-on: ubuntu-latest
  #      steps:
  #        - uses: actions/checkout@v4
  #          with:
  #            # Disabling shallow clones is recommended for improving the relevancy of reporting
  #            fetch-depth: 0
  #        - name: SonarQube Scan
  #          uses: SonarSource/sonarqube-scan-action@v5.2.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
  #          env:
  #            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  publish_docker_image:
    runs-on: ubuntu-latest
    #    needs: sonarqube-install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      # todo Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3 # todo docker/login-action@v4 not working don't try
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - name: Set up JDK 11
      #        uses: actions/setup-java@v4
      #        with:
      #          java-version: '17'
      #          distribution: 'adopt'

      - name: Push image to DockerHub
        run: |
          docker build -t spring-application-github .
          docker tag spring-application-github srinu641/spring-application-github:v1.0
          docker push srinu641/spring-application-github:v1.0

      - name: List Of Docker Images
        run: |
          docker images
          docker ps -a
          docker ps 

      - name: install Trivy
        run: |
          sudo apt-get install wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy    

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull srinu641/spring-application-github:v1.0

      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: srinu641/spring-application-github:v1.0
  #          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-application:V1.01
  k8s-deploy:
    runs-on: ubuntu-latest
    #    needs: publish_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0  # get all history of all branches and tags

      - name: Install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.7/2024-12-12/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

---

#Error
# a step cannot have both the `uses` and `run` keys
# Missing download info for docker/login-action@v4
#every step must define a `uses` or `run` key